### ISSUE TITLE
【建议】能否给删除文件增加删除提醒选项呢...

### ISSUE THREAD

**Issue by Noah1995** [Semibold/Weibo-Picture-Store#100]
1丶
能否给删除文件增加删除提醒选项呢...
还有最好能增加打开微相册选项...

2丶
现在这样图片会显示不完整...
能不能增加类似[二箱搜图](https://chrome.google.com/webstore/detail/noobox-search-by-image/kidibbfcblfbbafhnlanccjjdehoahep)这样的图片墙和￼图片列表视图
而且gif丶webp丶动态apng格式....
可以不用打开也可以直接可以动...
![【2019 06 26】【18∶00∶34】](https://user-images.githubusercontent.com/25548230/60171043-5ac79600-983c-11e9-8b16-19e208611d9d.gif)

**Comment by Aqours** [comment]
“删除”只是从相册中移除这个图片，并不会造成图片不能访问。并不明白增加删除提醒的意义，对于某些用户来说，这显得有些冗余。

打开微相册功能。这个其实是有的，不过是在页面底部，由于后期的设计改动造成用户大部分时间看不到这个选项（个人看来这个功能用的人比较少）。有待改进

图片列表/图片墙的功能。不打算支持图片列表，由于图片一般没有标题等其他有用的信息，展示上存在很大的问题，如果需要完整的图片，可以通过微相册查看。图片墙看起来可以实现

动态图问题。为了加载速度更快，历史记录里的图都是截切后的特定尺寸，因此动态图会变成静态图。对于动辄10+M的图来说，加载速度是优先考虑的问题。
