### ISSUE TITLE
【建议】能否增加ezgif网站的功能...

### ISSUE THREAD

**Issue by Noah1995** [Semibold/Weibo-Picture-Store#101]
1丶
因为贴吧限制最大4.99mQQ表情最大6m...
我经常用这个网站优化减小和修改录制的gif...
能否做到添加和删除按钮一样直接可以打开目前图片并自己优化...
https://ezgif.com/optimize
![【Snipaste】【2019-07-18】No 174554](https://user-images.githubusercontent.com/25548230/61447702-07042480-a984-11e9-9645-ea2c7ddfd8a9.jpg)

2丶
这个上传记录能否增加在这个独立窗口打开呢....
可以不要新建标签页也直接切换...
反正就是这个效果图...
![bbb0e787-2155-45b7-8a09-cdf86134e031](https://user-images.githubusercontent.com/25548230/61448437-7890a280-a985-11e9-860e-5d9d7198c898.png)

**Comment by Aqours** [comment]
1. 你的这个需求跟扩展没啥关系，这个扩展只调用微博相关的接口，图片压缩不在此扩展的范围。不过你的需求应该可以写个tampermonkey脚本实现

2. 上传记录是为了找以前的图片，你上传的时候应该用不到才对。不是很明白你的使用场景是什么样的
