### ISSUE TITLE
"此扩展程序可能已损坏。"

### ISSUE THREAD

**Issue by gzlock** [Semibold/Weibo-Picture-Store#102]
**Describe the bug**

Chrome扩展中显示“此扩展程序可能已损坏。”
![image](https://user-images.githubusercontent.com/2311740/63330948-4351e880-c367-11e9-990b-1e2146a06fac.png)

还有另外一个问题：
在微博网页登录的账号和密码是对的，但是在扩展中登录相同的账号和密码却一直显示账号或密码错误。

**Comment by gzlock** [comment]
尝试用过那个“修复”按钮的功能，但是重启Chrome后依然显示“已损坏”

**Comment by gzlock** [comment]
打开收集错误，收集到这个错误：
```
The connection used to load resources from https://login.sina.com.cn used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later. See https://www.chromestatus.com/feature/5654791610957824 for more information.
```
应该就是TLS版本低于1.2导致登录微博失败和显示“已损坏”

**Comment by Aqours** [comment]
1. 移除扩展重新安装。我在Canary及稳定版下测试都正常
2. 登录问题，请你重现这种情况然后在扩展图标上右键导出日志，贴上来看看
3. TLS版本过低是微博SSL配置的问题，这个属于警告，目前不会影响正常使用

**Comment by gzlock** [comment]
又好了😓
