### ISSUE TITLE
能否支持 Firefox 版本？

### ISSUE THREAD

**Issue by runningcheese** [Semibold/Weibo-Picture-Store#104]
感谢作者的付出！

不知道能否支持 Firefox 版本，现在 chrome 和 firefox 的拓展已经极其相似，几乎稍加修改就可以推出 Firefox 版本了？ 

希望作者后续能出 Firefox 版本!!

再次感谢！

**Comment by Aqours** [comment]
Download link: https://addons.mozilla.org/en-US/firefox/addon/weibo-picture-store/
