### ISSUE TITLE
上传图片遇到问题

### ISSUE THREAD

**Issue by HuiProgramer** [Semibold/Weibo-Picture-Store#105]
**Bug 描述**
您好，我这边上传图片时遇到了 **微博登录信息校验成功，可是。。。图片上传失败了** 的问题

普通提示为： **自动丢弃文件大小超过20m及文件格式不受支持的**

我的图片为：不超过**1M**的**png**图片。
也测试过其它jpg，等以前上传成功的图片都是这样。

截图:
![2345截图20191021102608.png](https://i.loli.net/2019/10/21/HG23KDhoENqyjwm.png)

**Comment by Aqours** [comment]
建议把日志贴上来便与分析。

获取日志方法：在扩展图标上右击，点击【导出日志】

**Comment by HuiProgramer** [comment]
**日志如下**：

------------------ Metadata Starting ------------------
Version: 5.7.0
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
------------------ Metadata Finished ------------------
[WARN.]-[2019-10-21T02:31:24.792Z]-[Utils.fetch]-[Forbidden]-[http://picupload.weibo.com/interface/pic_upload.php?s=xml&ori=1&data=1&rotate=0&wm=&app=miniblog&mime=image%2Fpng]
[DEBUG]-[2019-10-21T02:31:24.930Z]-[getUserStatus]-[用户处于登录状态]-[N/A]
[WARN.]-[2019-10-21T02:31:24.931Z]-[setUserStatus]-[检测到用户处于登录状态，中断激活用户登录状态的操作]-[N/A]
[WARN.]-[2019-10-21T02:31:24.934Z]-[uploader]-[请求用户登录状态时，捕获到异常]-[{"login":true}]
[WARN.]-[2019-10-21T02:31:24.940Z]-[WeiboUpload]-[immediately: true, size: 0]-[事件触发的时机不正确]
[WARN.]-[2019-10-21T05:00:17.695Z]-[Utils.fetch]-[Forbidden]-[http://picupload.weibo.com/interface/pic_upload.php?s=xml&ori=1&data=1&rotate=0&wm=&app=miniblog&mime=image%2Fjpeg]
[DEBUG]-[2019-10-21T05:00:18.079Z]-[getUserStatus]-[用户处于登录状态]-[N/A]
[WARN.]-[2019-10-21T05:00:18.079Z]-[setUserStatus]-[检测到用户处于登录状态，中断激活用户登录状态的操作]-[N/A]
[WARN.]-[2019-10-21T05:00:18.081Z]-[uploader]-[请求用户登录状态时，捕获到异常]-[{"login":true}]
[WARN.]-[2019-10-21T05:00:18.089Z]-[WeiboUpload]-[immediately: true, size: 0]-[事件触发的时机不正确]

**Comment by Aqours** [comment]
你升级下扩展就好了。你的扩展版本太旧了，最新版是5.11.1

发自我的iPhone

**Comment by HuiProgramer** [comment]
非常感谢大大，请问大大有国内的下载方式吗？我这边没翻墙，无法更新

**Comment by Aqours** [comment]
请参考文档描述 https://github.com/Semibold/Weibo-Picture-Store/blob/master/docs/get-crx-file.md

发自我的iPhone
