### ISSUE TITLE
请教2个关于域名的问题

### ISSUE THREAD

**Issue by OrdinaryYZH** [Semibold/Weibo-Picture-Store#108]
* 我发现微博的相片的域名会改变，比如现在看到wx1开头，之前是其他，这种域名改变了很明显会导致之前的域名的图片打不开了，这种情况如何解决呢？PS：我只能改成现在的域名了。。
* 还有插件上传的域名地址是如何得到的呢？

**Comment by Aqours** [comment]
1. 更换新链接
2. https://github.com/Semibold/Weibo-Picture-Store/blob/eebe66173610a797dab487a0a3b0214bc77a363e/src/scripts/sharre/constant.js#L136

**Comment by OrdinaryYZH** [comment]
> 1. 更换新链接
> 2. https://github.com/Semibold/Weibo-Picture-Store/blob/eebe66173610a797dab487a0a3b0214bc77a363e/src/scripts/sharre/constant.js#L136

如果失效了，新的域名也是手动修改代码？

**Comment by Aqours** [comment]
是的。你可以自己做个重定向，这样后面再更换后，修改比较方便

**Comment by OrdinaryYZH** [comment]
> 是的。你可以自己做个重定向，这样后面再更换后，修改比较方便

没看懂，怎么说起重定向了。我的情况是，笔记都是使用markdown的，域名改了后就又要修改才可以显示。
还有个问题，这些tva1,tva2是怎么得来的呢？

**Comment by Aqours** [comment]
忽略重定向那部分。笔记本应该有全局替换功能，替换下就可以。
域名前缀那个是去微博上分析得到的。
