### ISSUE TITLE
火狐右键上传提示：无法读取远程文件

### ISSUE THREAD

**Issue by HayashiKaori** [Semibold/Weibo-Picture-Store#110]
https://mmbiz.qpic.cn/mmbiz_jpg/lxiaqLXbic4iceHoVcWMkTN3YkYMEb7yS3c1Kkm2UKY8oiatjY0fvtp3DDu58lyEYrDF5vjj59C9F8vpktaTz36TOg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1

类似这样的图片链接，貌似不行。

**Comment by Aqours** [comment]
请在选项中开启伪造 Referer 可解决此问题。
由于版本变更导致，具体请查看更新日志 https://github.com/Semibold/Weibo-Picture-Store/blob/master/changelog.md

**Comment by HayashiKaori** [comment]
> 
> 
> 请在选项中开启伪造 Referer 可解决此问题。
> 由于版本变更导致，具体请查看更新日志 https://github.com/Semibold/Weibo-Picture-Store/blob/master/changelog.md

试过了，提示依旧。
我的环境是 win10 + firefox74.0 64bit + 图床5.12.0。
估计是兼容性问题。
十分感谢你的答复！

**Comment by Aqours** [comment]
请提供具体页面方便调试

**Comment by HayashiKaori** [comment]
测试网页：https://www.nogizaka46.net.cn/pic/memberInfo.html?name=blog
先点击左上角红衣女孩，页面会刷出许多图片。
随便选一张都无法右键上传。

**Comment by Aqours** [comment]
火狐扩展后台页面有跨域限制，这个和 Chrome 扩展不一样。
另外伪造 Referer 的时候服务端返回 `x-tengine-error: denied by Refer ACL`，看起来是有 Referer 白名单。因为页面用了 `<meta name="referrer" content="no-referrer"/>` 省略了 Referer，所以没有问题。

有空会修下这个问题，提供一个可控的伪造 Referer 方式。

**Comment by Aqours** [comment]
你最开始给的图片，开启 Referer 伪造是可以上传的。网站上不能上传主要还是网站本身是盗链，导致伪造的 Referer 无效。

**Comment by Aqours** [comment]
5.12.3 已更新

**Comment by HayashiKaori** [comment]
更新后问题解决了，您真是人类之光。
不过，我又发现一个小问题，在 B 站测试把 HTML5 视频的当前帧上传为 JPG 图像的时候，
右键选择上传视频帧毫无反应，也没有上传到相册。
总之，非常感谢~
