### ISSUE TITLE
火狐浏览器该功能失效：HTML5 视频的当前帧上传为 JPG 图像

### ISSUE THREAD

**Issue by HayashiKaori** [Semibold/Weibo-Picture-Store#111]
win10 + ff74.0 + 微博图床 5.12.4
在 B 站测试把 HTML5 视频的当前帧上传为 JPG 图像的时候，
右键选择上传视频帧毫无反应，也没有上传到相册。
总之，非常感谢~

**Comment by Aqours** [comment]
火狐的扩展描述里有已知问题说明：无法捕获 video.src 为 blob 的视频。
而 B 站的是 blob 视频(ノへ￣、)

**Comment by HayashiKaori** [comment]
原来是这个意思 好的谢谢！
