### ISSUE TITLE
当上传.svg格式时失败

### ISSUE THREAD

**Issue by OrdinaryYZH** [Semibold/Weibo-Picture-Store#113]
**Describe the bug**

不支持svg吗？但是我看文档说是支持的呢

![image](https://user-images.githubusercontent.com/10287222/84561083-06cefd80-ad7c-11ea-8d14-dbd323d2d4a2.png)

当上传.svg格式时失败并有以上提示

并且在.svg的页面中也没有"把这种图片上传到微相册"的选项，例如这个链接：https://lotabout.me/2020/QQA-Isolation-Level-of-Database/P1-dirty-read.svg

**Comment by Aqours** [comment]
谢谢反馈，5.12.7 已修复。商店中更新较慢，请耐心等待。

**Comment by Aqours** [comment]
> 并且在.svg的页面中也没有"把这种图片上传到微相册"的选项，例如这个链接：https://lotabout.me/2020/QQA-Isolation-Level-of-Database/P1-dirty-read.svg

使用浏览器单独打开SVG时，它是一个文档（类似HTML文档）而不是图片，因此没有右键菜单。
