### ISSUE TITLE
不能登陆了

### ISSUE THREAD

**Issue by David318** [Semibold/Weibo-Picture-Store#114]
**Describe the bug**

今天传图的时候发现传图失败了，登陆也失败

**Comment by Aqours** [comment]
请把日志贴上来

**Comment by David318** [comment]
不知道这样可不可以
——————————————
错误
警告  [signInByUserAccount] json: [object Object]; reason: Error: needCaptcha: 0

/*
 * Copyright (c) 2018 The Weibo-Picture-Store Authors. All rights reserved.
 * Use of this source code is governed by a MIT-style license that can be
 * found in the LICENSE file.
 */

import { LogStore } from "../background/persist-store.js";

const MAXIMUM_LOGS = 2000;
const backWindow = chrome.extension.getBackgroundPage();

/**
 * @static
 * @desc Can NOT be used in content scripts.
 */
export class Log {
    /**
     * @private
     */
    static get store() {
        if (backWindow === self) {
            return LogStore;
        } else {
            return backWindow.coreAPIs.LogStore;
        }
    }

    /**
     * @public
     */
    static get LEVEL() {
        return { debug: "debug", warn: "warn", error: "error" };
    }

    /**
     * @typedef {Object} ErrObject
     * @property {string} module                                    - 所属模块
     * @property {string|Error|DOMError|DOMException} [error]       - 抛出的信息
     * @property {string|Object} [remark]                           - 可读的信息
     */

    /**
     * @private
     * @param {ErrObject} obj                      - 注意：此对象的内容会被更改
     * @param {string} [type]                      - keyof Log.LEVEL
     * @return {boolean}
     */
    static add(obj, type = Log.LEVEL.debug) {
        const types = Object.keys(Log.LEVEL);
        const info = { error: "", remark: "" };

        if (!types.includes(type)) {
            console.warn("Invalid `type` parameter");
            return false;
        }

        while (Log.store.size >= MAXIMUM_LOGS) {
            const value = Array.from(Log.store).shift();
            Log.store.delete(value);
        }

        if (typeof obj.remark === "string") {
            info.remark = obj.remark;
        } else if (obj.remark) {
            try {
                info.remark = JSON.stringify(obj.remark);
            } catch (e) {
                console.warn(e);
            }
        }

        if (typeof obj.error === "string") {
            info.error = obj.error;
        } else if (obj.error) {
            const error = obj.error;
            if (error && typeof error.message === "string") {
                info.error = error.message;
            }
        }

        const fd = Object.assign(obj, info, { type, timestamp: Date.now() });

        Log.store.add(fd);

        if (DEBUG && typeof console[type] === "function") {
            console[type](`[${fd.module}]`, fd.remark || fd.error);
        }

        return true;
    }

    /**
     * @public
     * @param {ErrObject} obj
     */
    static d(obj) {
        Log.add(obj, Log.LEVEL.debug);
    }

    /**
     * @public
     * @param {ErrObject} obj
     */
    static w(obj) {
        Log.add(obj, Log.LEVEL.warn);
    }

    /**
     * @public
     * @param {ErrObject} obj
     */
    static e(obj) {
        Log.add(obj, Log.LEVEL.error);
    }

    /**
     * @public
     * @param {string[]} [types]
     * @return {string}
     */
    static serialize(types = Object.keys(Log.LEVEL)) {
        const caches = [];
        const padNum = Math.max(...types.map(x => x.length));
        caches.push("------------------ Metadata Starting ------------------");
        caches.push(`Version: ${chrome.runtime.getManifest().version}`);
        caches.push(`User-Agent: ${self.navigator.userAgent}`);
        caches.push("------------------ Metadata Finished ------------------");
        Log.store.forEach((k, v) => {
            if (types.includes(v.type)) {
                // prettier-ignore
                caches.push(`[${v.type.toUpperCase().padEnd(padNum, ".")}]-[${new Date(v.timestamp).toISOString()}]-[${v.module}]-[${v.error}]-[${v.remark}]`);
            }
        });
        return caches.join("\r\n");
    }

    /**
     * @public
     */
    static download() {
        const blobUrl = URL.createObjectURL(new Blob([Log.serialize()], { type: "text/plain" }));
        const destroy = downloadDelta => {
            if (downloadDelta.endTime || downloadDelta.error) {
                URL.revokeObjectURL(blobUrl);
                if (chrome.downloads.onChanged.hasListener(destroy)) {
                    chrome.downloads.onChanged.removeListener(destroy);
                }
            }
        };
        chrome.downloads.onChanged.addListener(destroy);
        chrome.downloads.download({
            url: blobUrl,
            filename: "Weibo-Picture-Store_logs.txt",
        });
    }
}

**Comment by Aqours** [comment]
在 Chrome 扩展栏上的改扩展图标上右击，点击导出日志。

**Comment by David318** [comment]
------------------ Metadata Starting ------------------
Version: 5.12.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
------------------ Metadata Finished ------------------
[DEBUG]-[2020-07-27T02:21:06.067Z]-[requestUserCaptcha]-[]-[获取用户信息成功]
[WARN.]-[2020-07-27T02:21:06.069Z]-[signInByUserAccount]-[json: [object Object]; reason: Error: needCaptcha: 0]-[]
[DEBUG]-[2020-07-27T02:21:32.432Z]-[requestUserCaptcha]-[]-[获取用户信息成功]
[WARN.]-[2020-07-27T02:21:32.432Z]-[signInByUserAccount]-[json: [object Object]; reason: Error: needCaptcha: 0]-[]
[DEBUG]-[2020-07-27T07:05:52.753Z]-[requestUserCaptcha]-[]-[获取用户信息成功]
[WARN.]-[2020-07-27T07:05:52.754Z]-[signInByUserAccount]-[json: [object Object]; reason: Error: needCaptcha: 0]-[]

**Comment by Aqours** [comment]
在扩展图标上右击，点击【选项】，确认已勾选【使用账号和密码登录】，然后点击【确认】，看下能否登录或者有什么提示

**Comment by David318** [comment]
普通提示
配置失败，请检查微博账户信息

**Comment by Aqours** [comment]
你开了二次验证了吗？没开的话，那可能是你的账号密码不对

**Comment by David318** [comment]
二次验证倒是没有，不过刚才我退出重登了下微博让我填短信验证码了。密码是没错的，昨天之前都正常使用，就在昨天传图的时候发现传不了图片，不知道啥情况。

**Comment by Aqours** [comment]
出现短信验证码的原因是你的账号异常，这种情况通常是频繁更换IP或者其他问题触发的。这个情况下没有办法使用扩展的自动登录功能，你可以取消勾选【使用账号和密码登录】后使用扩展。等到异常状态接触后再使用自动登录功能。

**Comment by David318** [comment]
明白了，谢谢指点
