### ISSUE TITLE
配置了账号密码，但是无法登录？

### ISSUE THREAD

**Issue by ulifuqiang** [Semibold/Weibo-Picture-Store#115]
![QQ截图20200815214455](https://user-images.githubusercontent.com/25083314/90313627-9772b700-df40-11ea-8f54-6e8576d343c8.png)

手动网页登陆，需要验证短信验证码才可以。插件登录框这里获取不到验证码 就登录失败了吗？

**Comment by Aqours** [comment]
请参考 https://github.com/Semibold/Weibo-Picture-Store/issues/114#issuecomment-664181684

**Comment by Aqours** [comment]
如果你开了登录二次验证，也不能使用自动登录。

**Comment by Aqours** [comment]
这是微博判断你的账号异常了
