### ISSUE TITLE
不知道为什么用不了了呀？

### ISSUE THREAD

**Issue by hizablet** [Semibold/Weibo-Picture-Store#118]
上传图片不显示了，好像域名换了：
https://wx4.sinaimg.cn

**Comment by Aqours** [comment]
https://wx4.sinaimg.cn/large/006G4xsfgy1gi1q0m11b8j30sg0fwwkg.jpg

可以显示，你访问上面的链接出现什么？

**Comment by hizablet** [comment]
> https://wx4.sinaimg.cn/large/006G4xsfgy1gi1q0m11b8j30sg0fwwkg.jpg
> 
> 可以显示，你访问上面的链接出现什么？

就是Chrome 插件打开之后上传图片有时候一直不显示，有时候又会显示

**Comment by Aqours** [comment]
麻烦你描述的清楚一点。是访问图片链接不显示，还是上传界面中的缩略图不显示？不显示的时候显示什么或者有什么错误信息？有问题的URL可以发一个？

**Comment by hizablet** [comment]
> 麻烦你描述的清楚一点。是访问图片链接不显示，还是上传界面中的缩略图不显示？不显示的时候显示什么或者有什么错误信息？有问题的URL可以发一个？

就是博客引用图床显示不出来…

**Comment by hizablet** [comment]
> 麻烦你描述的清楚一点。是访问图片链接不显示，还是上传界面中的缩略图不显示？不显示的时候显示什么或者有什么错误信息？有问题的URL可以发一个？

好像有时候可以有时候不显示，我重新上传了之后又可以了😂

**Comment by Aqours** [comment]
嗯，你的扩展是旧版的？新版不会生成 wx4.sinaimg.cn 这种前缀。

**Comment by hizablet** [comment]
> 嗯，你的扩展是旧版的？新版不会生成 wx4.sinaimg.cn 这种前缀。

我是Chrome的插件呀

**Comment by Aqours** [comment]
chrome://extensions/?id=pinjkilghdfhnkibhcangnpmcpdpmehk
访问这个链接，看下扩展版本

**Comment by hizablet** [comment]
> chrome://extensions/?id=pinjkilghdfhnkibhcangnpmcpdpmehk
> 访问这个链接，看下扩展版本

是：5.12.8，博主您好，请问下可以直接从粘贴板上直接上传吗

**Comment by hizablet** [comment]
> > chrome://extensions/?id=pinjkilghdfhnkibhcangnpmcpdpmehk
> > 访问这个链接，看下扩展版本
> 
> 是：5.12.8，博主您好，请问下可以直接从粘贴板上直接上传吗

我试了下可以直接Ctrl+V粘贴上传，太赞了！

**Comment by hizablet** [comment]
> chrome://extensions/?id=pinjkilghdfhnkibhcangnpmcpdpmehk
> 访问这个链接，看下扩展版本

博主有个问题就是上传速度有点慢，上传一个图片要等好久

**Comment by Aqours** [comment]
1. 本地的网路不好
2. 本地开了代理，导致接口走代理上去了
3. 微博掉登录了，需要检查登录（这种情况只有第一次会比较慢）
