### ISSUE TITLE
能否在复制全部的那个按钮里面把对应的本地文件名也显示出来

### ISSUE THREAD

**Issue by jobsfan** [Semibold/Weibo-Picture-Store#120]
**Describe the bug**
![11111](https://user-images.githubusercontent.com/3395025/161376558-c5061dc8-9642-4707-afa5-02abe43cdb1e.png)

例如 微博网址||本地文件名。

**Comment by Aqours** [comment]
没明白你的意思。
Copy All 就是复制当页已上传的同类型的所有连接。如果用户使用这个功能，默认知道复制的内容是什么，应该不需要额外提示。本地文件名对于图床没什么意义，什么场景下会需要文件名呢？

**Comment by jobsfan** [comment]
@Aqours 谢谢您的回复！

我上传到微博图床的图是有顺序的，图片引用是一个leaflet的js库，这个js会把图片编号，例如z_y_x.jpg（其中z表示缩放层级，y表示列，x表示行），我用了一个后端程序做映射，比如7_4_5.jpg我会把它映射到微博图床的一个url。

所以我需要知道这个映射关系。原本可以一对一的传，自己记录下这个对应关系，但是这个leaflet通过切片软件切出的贴片，多达1w多个，这个要手动一个个搞，就有点太难了。

你的这个浏览器插件已经很厉害了。我只是问问看。

再次感谢你的回复。

**Comment by Aqours** [comment]
你就是想要文件名和 URL 的一个映射关系吧。

那这个关系目前是有的，你可以复制非 URL 的其他三种类型，里面会带有文件名。比如：

```html
<img src="https://tvax2.sinaimg.cn/large/example.jpg" alt="filename" width="2302" data-width="2302" data-height="982">
```

其中 alt 中的内容就是不带后缀的文件名，你可以自己解析 img 标签中的 URL 和文件名即可。

**Comment by jobsfan** [comment]
@Aqours 
Get到了，非常感谢！！
