### ISSUE TITLE
图片返回显示403这里提供一下解决方法

### ISSUE THREAD

**Issue by HuYihe2008** [Semibold/Weibo-Picture-Store#126]
- 1.将图片的域名转换为 snimg.jamyido.top 进行访问
- 2.将图片的域名转换为 121.4.132.167:31043 进行访问
- 3.使用百度的代理：https://image.baidu.com/search/down?url=微博链接    （会直接下载不预览）

**Comment by dtlnor** [comment]
jamyido.top 不是新浪的域名吧？这个是你自己架构的网站的域名吗
121.4.132.167 也是一个不知来历的网站
如果可以添加一下说明会更好

**Comment by Wangijun** [comment]
我的哥，貌似第一种方式失效了

**Comment by Wangijun** [comment]
第二种也已经失效，第三种目前尚可。

**Comment by Wangijun** [comment]
第三种无法使用浏览器的缓存，但是网速尚可的情况下浏览也还行。
