### ISSUE TITLE
2023 年，微博图床 403 全失效，一个方法秒解决！

### ISSUE THREAD

**Issue by runningcheese** [Semibold/Weibo-Picture-Store#127]
做为国内最好的“微博图床”（没有之一），经过了多次限制整改都“挺”了过来，然后这一次的力度可谓历史空前。

2023 年初，所有微博图床的图片都不再可以访问，并且显示为“403 Forbidden”。

微博图床真的要告别历史，没办法再“白票”了吗？

今天再给它“续命”一次。

**具体这里：**

[https://mp.weixin.qq.com/s/LFX37OvOEUcGSdWYD0XWxQ](https://mp.weixin.qq.com/s/LFX37OvOEUcGSdWYD0XWxQ)

**太长不看：**

也就是说，已经阵亡的微博图床，在原先图片链接的前面加上 
https://image.baidu.com/search/down?url=
即可恢复访问。

**备用服务：**

我找到了 4 个图片缓存服务网站，可以让微博图片重新恢复访问。

WordPress：
https://i0.wp.com/图片地址    （图片地址要掉 https://）

Weserv.nl：
https://images.weserv.nl/?url=图片地址

百度 1：
https://image.baidu.com/search/down?url=图片地址

百度 2：
https://gimg2.baidu.com/image_search/&app=2020&src=图片地址    （图片地址要去掉 https://）

**最后的最后：**

希望作者还能继续更新这个扩展，这扩展是目前村里唯一的希望。

**Comment by Rhin0cer0s2022** [comment]
支持支持，太棒了，解决了燃眉之急啊
好奇一下，这些缓存服务器是怎么找的呢？

**Comment by chenjia404** [comment]
提供一个新的方案

https://cdn.ipfsscan.io/weibo/large/488c829bgw1es31sl8s7rg2091066gqc.gif

把域名部分改成 https://cdn.ipfsscan.io/weibo/

**Comment by Wangijun** [comment]
https://github.com/Semibold/Weibo-Picture-Store/issues/127#issuecomment-1546823483
这个前段时间不能用了，现在又可以使用了。

**Comment by crrashh1542** [comment]
现在似乎可以用 lz.sinaimg.com 这个域名了，配置下referrer就行
