### ISSUE TITLE
右键上传后自动复制链接到剪贴板功能取消了？

### ISSUE THREAD

**Issue by hbzhzjh** [Semibold/Weibo-Picture-Store#61]
这几天用着发现右键上传后直接粘贴不了了，这个功能取消了吗？挺好用的啊

**Comment by Aqours** [comment]
这个功能被移除掉了。静默去改变用户的剪切板会导致剪切板已有的内容被清掉，这种方式并不好。

后续会提供一个是否开启的选项并加上这个功能。5.1.0 的版本是从测试版迁移过来的，因此没有来得急加这个功能。

详情请查看 4.x 及 5.x 版本的更新日志 https://github.com/Semibold/Weibo-Picture-Store/blob/master/changelog.md#510

**Comment by sli1989** [comment]
默认复制不是更好。。本来就是想取得链接地址呀。。

**Comment by Aqours** [comment]
5.1.1 版本已临时恢复此功能
