### ISSUE TITLE
微博信息卡能否在当前访问的域名是微博时候不显示

### ISSUE THREAD

**Issue by igacc** [Semibold/Weibo-Picture-Store#64]
因为微博贴图肯定有博主信息，鼠标在用户头像上时还会出现官方的信息卡，会显得多余，
目前仅有全局开关，如果能在开启时候排除weibo.com weibo.cn等域名就更好用了

**Comment by Aqours** [comment]
5.2.2 新增 `Alt+Shift+C` 来禁用/启用当前域名下的微博信息卡功能。详情可以查看 [README.md](https://github.com/Semibold/Weibo-Picture-Store/blob/master/README.md)

**Comment by igacc** [comment]
谢谢

**Comment by ykfq** [comment]
原来是这个插件导致的我在任意网站把鼠标指向我图床中图片时都会显示博主的问题，吓得我以为浏览器哪里出了问题

**Comment by Aqours** [comment]
@ykfq 可是这个功能默认是关闭的呀
