### ISSUE TITLE
扩展导致 Gmail 出现一堆控制台错误

### ISSUE THREAD

**Issue by Love4Taylor** [Semibold/Weibo-Picture-Store#66]
嘛 虽然似乎是不影响使用. (用户信息卡选项已关闭
![](https://wx1.sinaimg.cn/large/af997d39gy1fu0t6ch5iqj211y0lcgry.jpg)

**Comment by Aqours** [comment]
这是 iframe 中获取顶层的 url 时报的一个错，会导致注入脚本注入失败，对其他功能没什么影响，下个版本修一下
