### ISSUE TITLE
Mac系统下无法成功上传图片，上传记录显示“获取图片失败”

### ISSUE THREAD

**Issue by JohnReddyZhang** [Semibold/Weibo-Picture-Store#69]
上传图片有进度提示，但是“成功”后界面无变化
![jietu20180809-121643](https://user-images.githubusercontent.com/15935574/43914666-1d6c4ad2-9bce-11e8-85a6-01dbad46e419.jpg)

![jietu20180809-121348](https://user-images.githubusercontent.com/15935574/43914599-eb3c58a4-9bcd-11e8-8b20-3a7a1670db9a.jpg)
偶尔收到这一提示

![jietu20180809-121319](https://user-images.githubusercontent.com/15935574/43914576-e029442c-9bcd-11e8-960b-ae68330359fc.jpg)
无法查看已上传图片

是否需要单独登陆微博？微博是不是需要什么特殊设置？

**Comment by Aqours** [comment]
打开 http://photo.weibo.com 看下你的账号是否处于异常状态

**Comment by JohnReddyZhang** [comment]
打开之后刷新很多次才能打开，一直在“正在登录”页面redirect，直到打开微博主页才能打开相册。
打开微博相册页面以后尝试上传，依然显示
![error](https://user-images.githubusercontent.com/15935574/43938260-3d14880e-9c28-11e8-8281-05bb3f810ce2.jpg)

是不是与我设置了登陆需要验证手机号才导致的问题……

**Comment by Aqours** [comment]
![image](https://user-images.githubusercontent.com/8586286/43938387-e6276cc8-9c95-11e8-83ec-5f47728a60ed.png)
你打开扩展页面按照图上的步骤打开界面，然后上传一张图或者打开历史纪录页面，把图中红色箭头处的内容截图发上来看一下。

打开 http://photo.weibo.com 一直在重定向的话，看下有没有其他微博相关的扩展，禁用试一下。退出微博重新登录试一下。

> 是不是与我设置了登陆需要验证手机号才导致的问题……

不清楚，我没有试过微博的二步验证

**Comment by JohnReddyZhang** [comment]
<img width="1054" alt="2018-08-21 21 06 33" src="https://user-images.githubusercontent.com/15935574/44438755-3056dd80-a586-11e8-8d9a-54ae64cc2c7d.png">

这是重启Chrome、确认登陆状态后按照操作步骤传图的截图

**Comment by Aqours** [comment]
看起来是上传失败了，需要请求头和返回结果看下具体是什么原因。按照下面两个图例截图传上来看一下，把 `Cookie` 打码。另外你看下 Cookie 是不是有三四行，如果 Cookie 过少的话，可能是被其他扩展修改过了，建议禁用其他扩展退出微博并重新登录试下。
![qq 20180822132157](https://user-images.githubusercontent.com/8586286/44444503-b79c6380-a60f-11e8-8772-155f862f1eac.png)
![qq 20180822132205](https://user-images.githubusercontent.com/8586286/44444504-b79c6380-a60f-11e8-949b-778f0ed14e1e.png)
