### ISSUE TITLE
微信文章图片无法上传！

### ISSUE THREAD

**Issue by wego0** [Semibold/Weibo-Picture-Store#72]
你好，微信文章图片无法上传！
如图：
![2018-08-18_151602](https://user-images.githubusercontent.com/37614489/44296895-e0fc7d00-a2f9-11e8-8b03-211f470e6ca2.jpg)

一直提示：不支持选中的文件格式

以前都是没问题的。请看下是什么问题。

日志正常：
[LOG..]-[2018-08-18T07:02:09.605Z]-[requestUserId]-[获取用户信息成功]-[N/A]
[LOG..]-[2018-08-18T07:02:09.927Z]-[CheckoutSpecialAlbumId]-[检出指定的微相册成功]-[N/A]
[LOG..]-[2018-08-18T07:02:10.424Z]-[requestPhotosFromSpecialAlbum]-[获取微相册的全部图片成功]-[N/A]
[LOG..]-[2018-08-18T07:04:42.506Z]-[requestUserId]-[获取用户信息成功]-[N/A]
[LOG..]-[2018-08-18T07:04:43.068Z]-[requestPhotosFromSpecialAlbum]-[获取微相册的全部图片成功]-[N/A]

**Comment by Aqours** [comment]
谢谢反馈，`5.4.1` 版本已修复这个问题

**Comment by wego0** [comment]
非常感谢。
没问题了。
