### ISSUE TITLE
不支持QQ浏览器低版本chrome内核

### ISSUE THREAD

**Issue by lijinfeng042** [Semibold/Weibo-Picture-Store#76]
**Describe the bug**
> 使用最新版QQ浏览器（10.2.1）安装失败，查看内核版本为63

**To Reproduce (Optional)**
> 在下面写出复现这个问题的步骤
1. QQ浏览器打开
2. 打开扩展链接
3. 添加显示为不支持

**Expected behavior**
> 期望支持使用

**Screenshots (Optional)**
> 在下面粘贴你遇到问题时的截图
![](https://ws1.sinaimg.cn/mw690/66cf5bc0ly1fv39eaj6ugj210r0gfn0q.jpg)

**Comment by Aqours** [comment]
本扩展仅支持 Chrome 66+，如果你使用版本较低的内核，可以尝试其他同类型的扩展，比如：https://chrome.google.com/webstore/detail/%E6%96%B0%E6%B5%AA%E5%BE%AE%E5%8D%9A%E5%9B%BE%E5%BA%8A/fdfdnfpdplfbbnemmmoklbfjbhecpnhf
