### ISSUE TITLE
能否在每一个版本的release里面增加crx直接下载？

### ISSUE THREAD

**Issue by colemanlee** [Semibold/Weibo-Picture-Store#81]
能否在每一个版本的release里面增加crx直接下载？

**Comment by Aqours** [comment]
什么样的场景需要直接使用crx？

**Comment by colemanlee** [comment]
国内浏览器的应用商城没有这个扩展下载，有无法连接外面世界的网络时，如果有crx直接下载安装，更加方便可以直接使用到。

--
by me

________________________________
发件人: L&H <notifications@github.com>
发送时间: 2018年12月12日 10:45
收件人: Semibold/Weibo-Picture-Store
抄送: Jeff Lee; Author
主题: Re: [Semibold/Weibo-Picture-Store] 能否在每一个版本的release里面增加crx直接下载？ (#81)


什么样的场景需要直接使用crx？

―

**Comment by Aqours** [comment]
此扩展仅支持Chromium 66+内核的浏览器，国内的常见浏览器内核都低于这个版本，因此不支持国内这些浏览器。当你无法访问Chrome商店，可以通过其他网站下载crx文件（某些网站是专门做这个的），个人没必要提供单独的crx文件。

**Comment by Aqours** [comment]
如果确实需要，可以自己生成一个crx文件，有时间我会在文档中提供一个教程。

**Comment by colemanlee** [comment]
> 此扩展仅支持Chromium 66+内核的浏览器，国内的常见浏览器内核都低于这个版本，因此不支持国内这些浏览器。当你无法访问Chrome商店，可以通过其他网站下载crx文件（某些网站是专门做这个的），个人没必要提供单独的crx文件。

谢谢，通过“https://chrome-extension-downloader.com/”以及下载链接“https://chrome.google.com/webstore/detail/pinjkilghdfhnkibhcangnpmcpdpmehk”可以直接下载。
