### ISSUE TITLE
能不能在满了一个相册后新建一个相册继续做图床。

### ISSUE THREAD

**Issue by ZhuangJiayu** [Semibold/Weibo-Picture-Store#83]
能不能在满了一个相册后新建一个相册继续做图床。我知道我有点贪心，薅羊毛有点过分哈哈......不过1000张的限制是有点少......

**Comment by Aqours** [comment]
可以，但目前历史记录只能查看一个相册的内容。

如何操作：
1. 找到名称为 `Weibo_Chrome` 的相册，把相册描述删除（http://photo.weibo.com/）
2. 新建一个相册，名称随意，描述里填写 `ImUfrNWhuFTTOXASFgdCVVv2ZUIquXrKjqiey2r95Kqudh6sjaBUWFdcwtlGEX2w`
3. 重启下此扩展即可（禁用后启用）
4. 打开历史记录验证是否生效

**Comment by Aqours** [comment]
5.5.0 已包含此功能
