### ISSUE TITLE
登录失败&使用问题

### ISSUE THREAD

**Issue by HuiProgramer** [Semibold/Weibo-Picture-Store#89]
**无法登录**

填写了手机号码和密码显示登录失败

**使用问题**

安装后不知道如何使用

**Comment by Aqours** [comment]
检查账号密码是否正确，还是无法登录在扩展图标上右击，导出日志贴上来

发自我的 iPhone

**Comment by HuiProgramer** [comment]
密码正确，显示配置失败，那个日志不会导 :flushed:

**Comment by HuiProgramer** [comment]
弄好了，给你带来困扰太抱歉了，感谢您
