### ISSUE TITLE
没有看到水印开启的设置呢

### ISSUE THREAD

**Issue by huanglw** [Semibold/Weibo-Picture-Store#92]
**看到最新的更新日志增加了水印添加功能，但是没有看到相关的设置**

**Comment by Aqours** [comment]
扩展的选项里有，【继承微博图片水印】就是了
![image](https://user-images.githubusercontent.com/8586286/55523460-f9b87800-56bb-11e9-8d70-04a7a05da6e8.png)

**Comment by lewindo** [comment]
找到了，感谢
