### ISSUE TITLE
微博图片无法外链了

### ISSUE THREAD

**Issue by ayconanw** [Semibold/Weibo-Picture-Store#95]
**Describe the bug**

在这里描述你遇到的问题（请删除这些说明性的语句）

**To Reproduce (Optional)**

> 在下面写出复现这个问题的步骤

**Expected behavior**

在这里写出你期望的行为或结果（请删除这些说明性的语句）

**Screenshots (Optional)**

在这里粘贴你遇到问题时的截图（请删除这些说明性的语句）

**Logs (Recommend)**

> 在下面粘贴扩展的日志。在扩展图标上右击【导出日志】可以下载日志文件

```text
// 在这里粘贴扩展的日志信息（请删除这些说明性的语句）
```

**Comment by mmmwhy** [comment]
的确无法外链了，之前开发的腾讯云存储(COS)可以重新拿回来吗

**Comment by Aqours** [comment]
微博外链有部分地区异常，属于微博的问题

@mmmwhy 去COS仓库下载就可以了

**Comment by mmmwhy** [comment]
@Aqours  那个微博图床测试版有一些小bug，比如右下角的提示不消失，提示上传成功但粘贴板内空白

**Comment by ayconanw** [comment]
应该是微博开始检测referrer了，加no referrer可解

**Comment by jamesrun** [comment]
不知道如何修复呢

**Comment by Aqours** [comment]
@mmmwhy 由于腾讯官方出了COS客户端，因此COS版本的扩展已不再更新了。你可以使用正式版本，如果需要COS功能，可以使用官方客户端哦

**Comment by ykfq** [comment]
> 应该是微博开始检测referrer了，加no referrer可解

具体怎么加呢，markdown 有办法解决吗？

**Comment by ykfq** [comment]
放到有道云笔记的 Markdown 链接，全部失效。。。

**Comment by Aqours** [comment]
@ykfq 使用 https 原图链接试下，还是 403，建议更换外链链接。目前不清楚微博外链策略是否要变动

**Comment by Aqours** [comment]
如果历史记录中的图片有 403 问题可以单独反馈，这种情况是可以处理的。

**Comment by vinci3123** [comment]
问题有办法处理么，我的图片连接好多都挂了。。本地的sublime text3+插件OnminiMarkupPreviewer都无法预览图片，必须要单独请求一次才可

**Comment by LKGin** [comment]
> 如果历史记录中的图片有403问题可以单独反馈，这种情况是可以处理的。

大大，是否可以增加一个功能，将图片链接转换为微博的短链接t.cn以解决外链问题（反代，norefer方案都不完美）？

**Comment by Aqours** [comment]
@LKGin 你有试过吗？原外链限制的话，短链应该也有的

**Comment by LKGin** [comment]
> @LKGin你有试过吗？原外链限制的话，短链应该也有的

测试过是可以的，对于403的图片。
短链跳转照理应该会带上原referer，but我是没看到有带上的...

**Comment by AlleriaWindy** [comment]
> > @LKGin你有试过吗？原外链限制的话，短链应该也有的
> 
> 测试过是可以的，对于403的图片。
> 短链跳转照理应该会带上原referer，but我是没看到有带上的...

我认为之所以行是因为t.cn会302到的是http而非https（即便你在t.cn前也加https），这波被403的都是https的http没受影响。（我测试过无锡ADSL电信、南京学校电信、南京教育网，都是这样不知道其他地方会不会不同）

**Comment by Aqours** [comment]
@LKGin 短链跳到原链会带 referrer，解决不了现有的问题。

目前可以使用 `tvax[1-4].sinaimg.cn` 代替之前的域名，这个域名暂时没有使用防盗链措施。
微博图片应该是启用了白名单模式，建议做好迁移图片的准备。

**Comment by AlleriaWindy** [comment]
前几天把sinaimg.cn换成sinaimg.in有效，但很快就失效了，估计tvax也不会长久。

**Comment by solider245** [comment]
哎，不知道后续怎么解决，我之前用微博图床是真的好用，现在估计要和大家一样，迁移到腾讯的COS了。
又是一次学习啊
