### ISSUE TITLE
希望把上传图片后的顶级域名从https://...cn改为in

### ISSUE THREAD

**Issue by AlleriaWindy** [Semibold/Weibo-Picture-Store#97]
面对最近检测referrer导致的403，有人发现把sinaimg.cn改为sinaimg.in，不用添加meta标签也能解决403，我在我的博客试了下，只要先用浏览器访问下.in域名对应的图片，以后就都能正常加载了。（我确定不是缓存，我在电脑上访问下图片，手机也能正常显示了）
另外，这次403好像暂时只涉及https，且要放在img标签等里面时，用作css的背景貌似不传递referrer所以不受影响，用http访问我这里没有任何问题。
不知道长久与否，欢迎大家一起测试、讨论。

**Comment by AlleriaWindy** [comment]
我又测了一会儿，发现in比cn速度慢，不知道是不是我网的问题。。。

**Comment by Aqours** [comment]
并不是所有地区都会403，暂时不清楚微博是否打算限制外链。暂时不会修改链接域名后缀
