### ISSUE TITLE
能否添加自定义复制格式？

### ISSUE THREAD

**Issue by shanlanCoding** [Semibold/Weibo-Picture-Store#98]
目前有多种的复制格式，但是唯独不能自定义。

由于微博开启了防盗链，有个解决方案是在img标签里添加一个属性：`referrerpolicy="no-referrer"`
如果是这样的话，那么我就需要重新定义一个贴图的函数，不能再单独的使用markdown贴图语法了，需要自定义一个图片的语法，例如：
`{% functionName xxx.com/sss.jpg args %}`
所以，能否增加自定义格式的复制链接？

**Comment by Aqours** [comment]
这种转换在md解析层做比较合理

另外，`referrerpolicy` 浏览器兼容性较差，用来反反盗链可能不妥

**Comment by shanlanCoding** [comment]
> 这种转换在MD解析层做比较合理
> 
> 另外，`referrerpolicy`浏览器兼容性较差，用来反反盗链可能不妥

嗯嗯，我自己写段js吧，匹配新浪的域名然后给img标签自动加上这个属性。

**Comment by shanlanCoding** [comment]
### 提供Hexo博客程序的解决新浪微博图床403的方法，理论上所有支持JavaScript的页面都可以用该方法：
# [解决新浪/微博图床图片403错误防盗链问题](https://blog.gobyte.cn/post/cfce32d8.html)
