### ISSUE TITLE
去相册里复制地址的时候只有http不是https了

### ISSUE THREAD

**Issue by TCP404** [Semibold/Weibo-Picture-Store#99]
**Describe the bug**

如果一开始没有复制地址或者后来去微博相册里复制地址的时候只有http没法https了

**Comment by Aqours** [comment]
你指的是历史记录？这里的链接直接使用接口返回的数据，没有处理。后续版本改成默认https

**Comment by TCP404** [comment]
> 你指的是历史记录？这里的链接直接使用接口返回的数据，没有处理。后续版本改成默认https

对啊。历史记录那里，点进去就没有https了。

**Comment by Aqours** [comment]
See https://github.com/Semibold/Weibo-Picture-Store/blob/master/changelog.md#5100
